name: publish

on:
  push:
    branches: [main]
  pull_request:

env:
  CNAME: polyquity-epfl.github.io
  SUB_PATH: ${{ github.ref != 'refs/heads/main' && format('.previews/{0}/', github.event.number) || '' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - run: echo "BASE_URL=https://${{ env.CNAME }}/${{ env.SUB_PATH }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - run: make
      - uses: zolacti/on@build
        with:
          base-url: ${{ env.BASE_URL }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ${{ env.SUB_PATH }}
          # TODO add cname of custom domain

      - uses: hasura/comment-progress@v2.3.0
        if: github.ref != 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: |
            ✨ Website successfully built ✨
            Preview can be seen here: ${{ env.BASE_URL }}
